### ISSUE TITLE
Checklist of todos for features to implement in the IK solver

### ISSUE THREAD

**Issue by mithi** [mithi/hexapod-robot-simulator#16]
# Notes:
- [x] limit beta and gamma ranges
- [x] Limit alpha to range between -90 to 90
- [x] When all left side or right side is above ground, make this an impossible pose.
- [x] Name the updated points of the updated hexapod their correct names, right now they're names is None
